server:
  port: 8085
  servlet:
    context-path: /api
keycloak:
  client-id: auth-service-v1
  client-secret: paYaiEgM4Ytg6DA3HUPcGTenoSJx8g72
  get-token-url: http://localhost:9090/realms/master/protocol/openid-connect/token
  issuer-url: http://localhost:9090/realms/master
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: redis-password
